config/routes.rb
GradStudents::Application.routes.draw do
  get "letter/show"

  devise_for :professors
  
  root to: "students#index"
  
  match 'students/incomplete_qualifier' => 'students#incomplete_qualifier'
  match 'students/incomplete_research' => 'students#incomplete_research'
  match 'students/incomplete_citi' => 'students#incomplete_citi'
  match 'students/committees' => 'students#committees'
  match 'students/funding' => 'students#funding'
  match 'professors/committees' => 'professors#committees'
  match 'fundings/edit' => 'fundings#edit', as: :edit_fundings
  match 'fundings/update' => 'fundings#update', as: :update_fundings, via: :put
  resources :professors
  resources :students
  resources :meetings
  resources :letters
  
  

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  has_many :meeting_attendances
  has_many :students, through: :meeting_attendances
  # has_and_belongs_to_many :students, uniq: true
  validates_presence_of :date
  
  def to_param
    "#{id} #{date.strftime("%b-%d-%y-%H%M")}".parameterize
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def index
    @meetings = Meeting.order('date DESC')
  end
  
  def show
    @meeting = Meeting.find(params[:id])
  end
  
  def new
    @meeting = Meeting.new
  end
  
  def edit
    @meeting = Meeting.find(params[:id])
  end
  
  def create
    @meeting = Meeting.new(params[:meeting])
    
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'New meeting was successfully created.' }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  def update
    @meeting = Meeting.find(params[:id])
    
    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_attendees.slim
table.table
  thead
    tr
      th Name
      th
  tbody#committee
    = hidden_field_tag "meeting[student_ids][]", nil
    - students.order('last_name').each do |student|
      tr.fields
        td
          = check_box_tag "meeting[student_ids][]", student.id, @meeting.students.include?(student), id: dom_id(student)
          = label_tag dom_id(student), student.full_name, class: "inline"

app/views/meetings/_form.html.slim
= simple_form_for @meeting, html: { class: "form-horizontal" } do |f|
  = f.input :date, input_html: { class: "datetime_select" }
  = f.input :notes
  = f.input "Attendees" do
    .tabbable
      ul.nav.nav-tabs
        li.active
          a href="#1" data-toggle="tab" Current Students
        li
          a href="#2" data-toggle="tab" Past Students
      .tab-content
        .tab-pane.active#1
          = render "attendees", students: Student.current_students
        .tab-pane#2
          = render "attendees", students: Student.past_students
    .form-actions
      = f.submit "Submit", class: "btn btn-primary"
      = link_to "Cancel", :back, class: "btn btn-cancel"

app/views/meetings/edit.html.slim
h1 Edit Meeting
= render :partial => "form"

app/views/meetings/index.html.slim
h1 Meetings
= link_to "New meeting", new_meeting_path, class: "hide-from-pdf"
table class="table table-striped"
  thead
    tr
      th Date
      th Attendees
      th Notes
      th 
  tbody
    - @meetings.each do |meeting|
      tr
        td = link_to display_date(meeting.date), meeting_path(meeting)
        td = meeting.students.count
        td = truncate(meeting.notes, length: 50)
        td
          ' #{link_to "Edit", edit_meeting_path(meeting)}
          ' #{link_to "Destroy", meeting_path(meeting), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}

app/views/meetings/new.html.slim
h1 New Meeting
= render :partial => "form"

app/views/meetings/show.html.slim
h2 = display_date(@meeting.date)

dl.dl-horizontal
  dt Notes
  dd = @meeting.notes || "(None)"
  dt.breathing-room Attendees (#{@meeting.students.count})
  - @meeting.students.order('last_name').each do |student|
    dd = link_to student.full_name, student
  dd


.form-actions.hide-from-pdf
  = link_to "Back", :back, :class => 'btn'
  = link_to "Edit", edit_meeting_path(@meeting), :class => 'btn'
  = link_to "Delete", meeting_path(@meeting), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn'