config/routes.rb
GradStudents::Application.routes.draw do
  get "letter/show"

  devise_for :professors
  
  root to: "students#index"
  
  match 'students/incomplete_qualifier' => 'students#incomplete_qualifier'
  match 'students/incomplete_research' => 'students#incomplete_research'
  match 'students/incomplete_citi' => 'students#incomplete_citi'
  match 'students/committees' => 'students#committees'
  match 'students/funding' => 'students#funding'
  match 'professors/committees' => 'professors#committees'
  match 'fundings/edit' => 'fundings#edit', as: :edit_fundings
  match 'fundings/update' => 'fundings#update', as: :update_fundings, via: :put
  resources :professors
  resources :students
  resources :meetings
  resources :letters
  
  

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_one :qualifier, dependent: :destroy
  has_many :committees, dependent: :destroy
  has_many :professors, through: :committees
  has_many :meeting_attendances
  has_many :meetings, through: :meeting_attendances
  accepts_nested_attributes_for :committees, allow_destroy: true, reject_if: proc { |a| a['professor_id'].blank? }
  accepts_nested_attributes_for :qualifier
  
  validates_associated :committees
  validates_presence_of :first_name, :last_name, :degree
  validates_uniqueness_of :last_name, scope: :first_name
  validates_format_of :panther_id, with: /\d\d\d\-\d\d\-\d\d\d\d/, allow_nil: true, allow_blank: true
  validates_numericality_of :stipend, :year_entered, :ms_year, :phd_year, allow_nil: true
  
  before_save :check_for_qualifier
  before_save :store_stipend_for_graduated_student
  
  def to_param
    "#{id} #{full_name}".parameterize
  end
  
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  
  def committee(options = {})
    case options
    when :ms
      professors.where('ms = true')
    when :phd
      professors.where('phd = true')
    when :ms_chair
      professors.where("ms_chair = true")
    when :phd_chair
      professors.where("phd_chair = true")
    when :ms_members
      professors.where('ms_chair = false AND ms = true')
    when :phd_members
      professors.where('phd_chair = false AND phd = true')
    end
  end
  
  def phd_student?
    degree == "PhD"
  end
  
  def ms_student?
    degree == "Masters"
  end
  
  def self.current_students
    self.where('status = ?', "Current student")
  end
  
  def self.past_students
    self.where('status != ?', "Current student")
  end
  
  def self.incomplete_qual
    self.includes(:qualifier).where('degree = ? AND (qualifiers.em = false OR qualifiers.quantum = false OR qualifiers.stat_mech = false OR qualifiers.class_mech = false)', "PhD")
  end
  
  def self.incomplete_research(options={})
    case options
    when :ms
      where('degree = ? AND alt_research_1 IS ?', 'Masters', nil)
    when :phd
      where('degree = ? AND (alt_research_1 IS ? OR alt_research_2 IS ?)', 'PhD', nil, nil)
    else
      incomplete_research(:ms) + incomplete_research(:phd)
    end
  end
  
  def self.incomplete_citi
    self.where('citi_online = false OR citi_discussion = false')
  end
  
  def build_default_qualifier
    self.build_qualifier do |t|
      t.em = false
      t.stat_mech = false
      t.class_mech = false
      t.quantum = false
      t.attempts = 0
      t.student_id = self.id
    end
  end
  
  def tests_passed
    # This doesn't feel right, but I don't have an alternative
    [:em,:stat_mech, :quantum, :class_mech, :biophysics, :astrophysics].map { |field| self.qualifier.send(field)}
        .keep_if { |t| t }
        .count
  end
  
  def passed_qualifier?
    tests_passed >= 4
  end
  
  def funding
    return stipend if unique_stipend    
    return nil unless phd_student?
    if passed_qualifier?
      puts "qual"
      Funding.postqual
    else
      Funding.prequal
    end
  end
  
  def set_graduated
    self.status = "Graduated"    
  end
  
  def set_graduated!
    self.set_graduated
    self.save!
  end
  
  def current_student?
    status == "Current student"
  end
  
  def self.funding_by_year(options = {})
    # returns a hash with [year] => [avg_stipend] pairs
    data = {}
    case options
    when :prequal
    Student.includes(:qualifier).all.keep_if { |stu| !stu.passed_qualifier? && !stu.externally_supported }
              .group_by(&:phd_year)
              .delete_if { |k,v| k.nil? || k > Time.now.year }
              .each do |key, value|
                new_array = value.map(&:funding)
                data[key] = (new_array.inject { |sum, n| sum + n }/new_array.length).to_i
               end
    when :postqual
      Student.includes(:qualifier).all.keep_if { |stu| stu.passed_qualifier? && !stu.externally_supported }
                .group_by(&:phd_year)
                .delete_if { |k,v| k.nil? || k > Time.now.year }
                .each do |key, value|
                  new_array = value.map(&:funding)
                  data[key] = (new_array.inject { |sum, n| sum + n }/new_array.length).to_i
                 end
    else
      Student.includes(:qualifier).all.group_by(&:phd_year)
                .delete_if { |k,v| k.nil? || k > Time.now.year }
                .each do |key, value|
                  new_array = value.map(&:funding)
                  data[key] = (new_array.inject { |sum, n| sum + n }/new_array.length).to_i
                 end
    end
    data.to_a.sort
  end

  
  private
  def check_for_qualifier
    if qualifier.nil?
      build_qualifier
    end
  end
  
  def store_stipend_for_graduated_student
    unless current_student?
      self.stipend = self.funding
      self.unique_stipend = true
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :admin_only, only: [:edit, :new, :create, :update, :destroy]
  
  # GET /students
  # GET /students.json
  def index    
    @current_students = Student.current_students.order('last_name')
    @past_students = Student.past_students.order('last_name')
    respond_to do |format|
      format.html
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.includes(:meetings, :qualifier, {:committees => :professor}).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new(ms_year: Time.now.year, phd_year: Time.now.year, status: "Current student")
    @student.build_default_qualifier
    @student.committees.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
    @student.build_default_qualifier if @student.qualifier.nil?
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  def incomplete_qualifier
    @students = Student.incomplete_qual.order('last_name')
  end
  
  def incomplete_research
    @ms_students = Student.incomplete_research(:ms).order('last_name')
    @phd_students = Student.incomplete_research(:phd).order('last_name')
  end
  
  def incomplete_citi
    @students = Student.current_students.incomplete_citi.order('last_name')
  end
  
  def committees
    @current_students = Student.includes(:committees, :professors).current_students.order('last_name')
    @past_students = Student.includes(:committees, :professors).past_students.order('last_name')
  end
  
  def funding
    data = Student.funding_by_year
    pre_data = Student.funding_by_year(:prequal)
    post_data = Student.funding_by_year(:postqual)
    max = data.map { |i| i[1] }.max + 1000
    min = data.map { |i| i[1] }.min - 1000
    @h = LazyHighCharts::HighChart.new('graph') do |f|
      f.options[:chart][:defaultSeriesType] = "line"
      f.series(name: "Pre-Qualifier", data: pre_data, color: "#B80332")
      f.series(name: "Post-Qualifier", data: post_data, color: "#3F779A")
      f.xAxis(categories: data.map { |i| i[0].to_s }, title: { text: "Year" })
      f.yAxis(max: max, min: min, title: { text: "Average Stipend" })
      # f.legend(enabled: false)
      f.title(text: "Average Stipend for Internally Supported Students")
    end
  end
  
  private
  def admin_only
    unless current_professor.admin?
      redirect_to :back, notice: "Must be an admin to perform this action"
    end
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_committee_fields.html.slim
tr.fields
  td = f.association :professor, label_method: :full_name, label: false, input_html: {class: "narrow"}, wrapper_html: { class: "table-select"}
  td.check = f.check_box :ms
  td.check = f.check_box :phd
  td.check = f.check_box :ms_chair
  td.check = f.check_box :phd_chair
  td = f.link_to_remove "X"

app/views/students/_committees.slim
table.table.table-bordered.table-condensed
  thead
    tr
      th Master Committee
      th PhD Committee
  tbody
    tr
      td.halfies
        table.table-condensed.nested-table
          - student.committees.select(&:ms_chair).map(&:professor).each do |chair|
            tr
              td
                = link_to chair.full_name, chair
                span.label Chair
          - student.committees.select(&:ms).delete_if { |i| i.ms_chair }.map(&:professor).each do |member|
            tr
              td
                = link_to member.full_name, member
      td.halfies
        table.table-condensed.nested-table   
          - if student.phd_student?
              - student.committees.select(&:phd_chair).map(&:professor).each do |chair|
                tr
                  td
                    = link_to chair.full_name, chair
                    span.label Chair
              - student.committees.select(&:phd).delete_if { |i| i.phd_chair }.map(&:professor).each do |member|
                tr
                  td
                    = link_to member.full_name, member
          - else
            tr
              td N/A

app/views/students/_form.html.slim
= simple_nested_form_for @student, html: { class: "form-horizontal" } do |f|
  = f.input "Basic Information" do
    = f.input :first_name, label: "First name", required: true
    = f.input :last_name, label: "Last name", required: true
    = f.input :sex, as: :select, collection: ["Male", "Female"], default: "Male", prompt: true, required: true
    = f.input :panther_id, label: "Panther ID", input_html: { id: "panther-id"}
    = f.input :email_2, label: "School E-mail"
    = f.input :email_2, label: "Personal E-mail"
    = f.input :lab_phone, label: "Lab Phone", input_html: { class: "phone-number" }
    = f.input :phone, label: "Personal Phone", input_html: { class: "phone-number" }
    = f.input :unique_stipend, label: "Unique Stipend?"
    = f.input :stipend, wrapper_html: { id: "stipend"}
    = f.input :externally_supported, label: "Externally Supported?"
    = f.input :notes
    
  = f.input "Degree Information" do
    = f.input :degree, as: :select, collection: ["Masters", "PhD"], default: "PhD", prompt: true, required: true
    = f.input :thesis_ms, label: "Thesis MS", wrapper_html: { class: "ms-only"}
    = f.input :year_entered
    = f.input :ms_semester, label: "MS Semester", collection: ["Spring", "Summer", "Fall"]
    = f.input :ms_year, label: "MS Year"
    = f.input :phd_semester, label: "PhD Semester", collection: ["Spring", "Summer", "Fall"], wrapper_html: {class: "phd-only"}
    = f.input :phd_year, label: "PhD Year", wrapper_html: {class: "phd-only"}
    
  = f.input "Degree Requirements" do
    = f.input :alt_research_1, label: "Alternate Research Skill"
    = f.input :alt_research_2, label: "Alternate Research Skill", wrapper_html: {class: "phd-only"}
    = f.input :status, as: :radio_buttons, collection: ["Current student", "Graduated", "Left program early"]
    = f.input :semester_left, label: "Semester student left program", collection: ["Spring", "Summer", "Fall"], wrapper_html: {class: "phd-only"}
    = f.input :year_left, label: "Year student left"
    
  = f.input "CITI Training" do
    = f.input :citi_online, label: "Online portion"
    = f.input :citi_discussion, label: "In-class Discussion"

  = f.input 'Committee Members' do
    table.table
      thead
        tr
          th Name
          th.check Masters
          th.check PhD
          th.check MS Chair
          th.check PhD Chair
          th
      tbody#committee
        = f.simple_fields_for :committees
    = f.link_to_add "Add a member", :committees, container: 'tbody#committee', fields_element: 'tr'
  = f.input 'Qualifying Exam' do
    = f.fields_for :qualifier do |qf|
      table.table
        thead
          tr
            th Exam
            th Finished
        tbody
          tr
            td = qf.label :em, "Electricity and Magnetism"
            td = qf.check_box :em
          tr
            td = qf.label :quantum, "Quantum Mechanics"
            td = qf.check_box :quantum
          tr
            td = qf.label :stat_mech, "Statistical Mechanics"
            td = qf.check_box :stat_mech
          tr
            td = qf.label :class_mech, "Classical Mechanics"
            td = qf.check_box :class_mech
          tr
            td = qf.label :biophysics, "Biophysics"
            td = qf.check_box :biophysics
          tr
            td = qf.label :astrophysics, "Astrophysics"
            td = qf.check_box :astrophysics
  .form-actions
    = f.submit "Submit", class: "btn btn-primary"
    = link_to "Cancel", :back, class: "btn btn-cancel"

app/views/students/_incomplete_research_table.slim
table.table
  thead
    tr
      th Name
      th E-mail
      th Degree
      th Alternate Research 1
      th Alternate Research 2
  tbody
    - students.each do |student|
        tr
          td = link_to student.full_name, student
          td = mail_to student.email_1
          td = student.degree
          td = student.alt_research_1
          td = student.ms_student? ? 'n/a' : student.alt_research_2

app/views/students/_qualifying_exam_list.slim
dt.breathing-room Qualifying Exams
- if student.passed_qualifier?
  dd
    - if student.qualifier.em
      span.label.label-success Electricity and Magnetism
    - else
      span.label E&M not completed
  dd 
    - if student.qualifier.stat_mech
      span.label.label-success Statistical Mechanics
    - else
      span.label Stat. Mech. not completed
  dd 
    - if student.qualifier.class_mech
      span.label.label-success Classical Mechanics
    - else
      span.label Class. Mech. not completed
  dd 
    - if student.qualifier.quantum
      span.label.label-success Quantum Mechanics
    - else
      span.label Quantum Mech. not completed
  dd 
    - if student.qualifier.astrophysics
      span.label.label-success Astrophysics
    - else
      span.label Astrophysics not completed
  dd 
    - if student.qualifier.biophysics
      span.label.label-success Astrophysics
    - else
      span.label Biophysics not completed
- else
  dd
    - if student.qualifier.em
      span.label.label-success Electricity and Magnetism
    - else
      span.label.label-important E&M Not Completed
  dd 
    - if student.qualifier.stat_mech
      span.label.label-success Statistical Mechanics
    - else
      span.label.label-important Stat. Mech. Not Completed
  dd 
    - if student.qualifier.class_mech
      span.label.label-success Classical Mechanics
    - else
      span.label.label-important Class. Mech. Not Completed
  dd 
    - if student.qualifier.quantum
      span.label.label-success Quantum Mechanics
    - else
      span.label.label-important Quantum Mech. Not Completed
  dd 
    - if student.qualifier.astrophysics
      span.label.label-success Astrophysics
    - else
      span.label.label-important Astrophysics Not Completed
  dd 
    - if student.qualifier.biophysics
      span.label.label-success Astrophysics
    - else
      span.label.label-important Astrophysics. Not Completed

app/views/students/_student_list.html.slim
table.table.table-striped.list
  thead
    tr
      th Name
      th E-mail
      th
      th
  tbody
    - students.each do |student|
      tr
        td 
          = link_to student.full_name, student_path(student), class: "filtered-by target_link"
          - if student.status == "Left program early"
            span.label.label-warning Left Early
        - if student.current_student?
          td = mail_to student.email_1, student.email_1, class: "filtered-by"
        - elsif student.email_2.present?
          td = mail_to student.email_2, student.email_2, class: "filtered-by"
        - else
          td = mail_to student.email_1, student.email_1, class: "filtered-by"
        td = student.degree
        td.hide-from-pdf = link_to "Edit", edit_student_path(student)

app/views/students/committees.slim
h1 Students and their committees
.tabbable
  ul.nav.nav-tabs
    li.active
      a href="#1" data-toggle="tab" Current Students
    li
      a href="#2" data-toggle="tab" Past Students
  .tab-content
    .tab-pane.active#1
      table.table
        thead
        tbody
          - @current_students.each do |student|
            tr
              td = link_to student.full_name, student
              td
                - unless student.committees.empty?
                  = render "committees", student: student
    .tab-pane#2
      table.table
        thead
        tbody
          - @past_students.each do |student|
            tr
              td = link_to student.full_name, student
              td
                - unless student.committees.empty?
                  = render "committees", student: student

app/views/students/edit.html.slim
h1 Edit Student
= render "form"

app/views/students/incomplete_citi.slim
h1 Students with incomplete CITI Training
p.hide-from-pdf = mail_to @students.map(&:email_1).delete_if(&:nil?).join(','), "E-mail these students"
table.table
  thead
    tr
      th Name
      th E-mail
      th.check Online
      th.check Discussion
  tbody
    - @students.each do |student|
        tr
          td = link_to student.full_name, student
          td = mail_to student.email_1
          td == ok_or_not_ok(student.citi_online)
          td == ok_or_not_ok(student.citi_discussion)

app/views/students/incomplete_qualifier.slim
h1 Students with incomplete Qualifying Exams
p.hide-from-pdf = mail_to @students.map(&:email_1).delete_if(&:nil?).join(','), "E-mail these students"
table.table
  thead
    tr
      th Name
      th E-mail
      th.check E&M
      th.check Quantum
      th.check Statistical
      th.check Classical
  tbody
    - @students.each do |student|
        tr
          td = link_to student.full_name, student
          td = mail_to student.email_1
          td == ok_or_not_ok(student.qualifier.em)
          td == ok_or_not_ok(student.qualifier.quantum)
          td == ok_or_not_ok(student.qualifier.stat_mech)
          td == ok_or_not_ok(student.qualifier.class_mech)
          

app/views/students/incomplete_research.slim
h1 Students with incomplete Alternate Research Skills
p.hide-from-pdf = mail_to (@phd_students + @ms_students).map(&:email_1).delete_if(&:nil?).join(','), "E-mail these students"
.tabbable
  ul.nav.nav-tabs
    li.active
      a href="#1" data-toggle="tab" PhD Students
    li
      a href="#2" data-toggle="tab" Masters Students
  .tab-content
    .tab-pane.active#1
      = render "incomplete_research_table", students: @phd_students
    .tab-pane#2
      = render "incomplete_research_table", students: @ms_students

app/views/students/index.html.slim
h1 Students
form.filterform.form-search.hide-from-pdf action="#"
  = text_field_tag "filterString", nil, class: "input-medium search-query"
  i.icon-remove.clear-search
= link_to "New Student", new_student_path, class: "hide-from-pdf"

.tabbable
  ul.nav.nav-tabs
    li.active
      a href="#1" data-toggle="tab" Current Students
    li
      a href="#2" data-toggle="tab" Past Students
  .tab-content
    .tab-pane.active#1
      = render "student_list", students: @current_students
    .tab-pane#2
      = render "student_list", students: @past_students

app/views/students/new.html.slim
h1 New Student
= render :partial => "form"

app/views/students/show.html.slim
- content_for :sidebar do
  li = link_to "View offer letter (pdf)", letter_path(@student.id, format: "pdf")

h2 
  = "#{salutation(@student)} #{@student.full_name}"
  - if @student.status == "Left program early"
    span.label.label-warning Left Early
  - if @student.status == "Graduated"
    span.label.label-success Graduated
h3 = formatted_degree(@student)
.row
  .span4
    dl.dl-horizontal
      dt E-mail
      dd = mail_to @student.email_1
      dd = mail_to @student.email_2
      dt Panther ID
      dd = @student.panther_id
      dt Lab Phone
      dd = number_to_phone @student.lab_phone
      dt Personal Phone
      dd = number_to_phone @student.phone
      dt Entered
      dd = @student.year_entered
      dt Stipend
      - if @student.externally_supported
        dd Externally Supported
      - elsif @student.ms_student?
        dd = "#{number_to_currency(Funding.ms, precision: 0)}/class"
      - else
        dd = number_to_currency(@student.funding, precision: 0)
      dt Alternate Research
      dd 
        - if @student.alt_research_1.present?
          = @student.alt_research_1
        - else
          span.label.label-important Alternate Research Not Met
      - if @student.phd_student?
        dd 
          - if @student.alt_research_2.present?
            = @student.alt_research_2
          - else
            span.label.label-important Alternate Research Not Met
      - if @student.current_student?
        dt Expected Masters
      - else
        dt Received Masters
      dd = "#{@student.ms_semester} #{@student.ms_year}"      
      - if @student.phd_student?
        - if @student.current_student?
          dt Expected PhD
        - else
          dt Received PhD
        dd = "#{@student.phd_semester} #{@student.phd_year}"
  .span5
    dl.dl-horizontal
      dt CITI Training
      dd
        - if @student.citi_online
          span.label.label-success Online Completed
        - else
          span.label.label-important Online Not Completed
      dd
        - if @student.citi_discussion
          span.label.label-success Discussion Completed
        - else
          span.label.label-important Discussion Not Completed
      = render "qualifying_exam_list", student: @student
      dt.breathing-room Meetings
      - @student.meetings.each do |meeting|
        dd = link_to display_date(meeting.date), meeting
.row
  .span4
    dl.dl-horizontal
      dt MS Committee
      - @student.committee(:ms_chair).each do |chair|
        dd 
          = link_to chair.full_name, chair
          span.label Chair
      - @student.committee(:ms_members).each do |member|
        dd = link_to member.full_name, member
  - if @student.phd_student?
    .span4
      dl.dl-horizontal
        dt PhD Committee
        - @student.committee(:phd_chair).each do |chair|
          dd 
            = link_to chair.full_name, chair
            span.label Chair
        - @student.committee(:phd_members).each do |member|
          dd = link_to member.full_name, member
.row
  .span8
    dl.dl-horizontal
      dt Notes
      dd = @student.notes

.form-actions.hide-from-pdf
  = link_to "Back", :back, :class => 'btn'
  = link_to "Edit", edit_student_path(@student), :class => 'btn'
  = link_to "Delete", student_path(@student), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn'