config/routes.rb
GradStudents::Application.routes.draw do
  get "letter/show"

  devise_for :professors
  
  root to: "students#index"
  
  match 'students/incomplete_qualifier' => 'students#incomplete_qualifier'
  match 'students/incomplete_research' => 'students#incomplete_research'
  match 'students/incomplete_citi' => 'students#incomplete_citi'
  match 'students/committees' => 'students#committees'
  match 'students/funding' => 'students#funding'
  match 'professors/committees' => 'professors#committees'
  match 'fundings/edit' => 'fundings#edit', as: :edit_fundings
  match 'fundings/update' => 'fundings#update', as: :update_fundings, via: :put
  resources :professors
  resources :students
  resources :meetings
  resources :letters
  
  

end

app/models/professor.rb
class Professor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, 
                  :last_name, 
                  :email, 
                  :password, 
                  :password_confirmation, 
                  :remember_me, 
                  :department_chair, 
                  :graduate_advisor, 
                  :undergraduate_advisor, 
                  :phone,
                  :legacy_id,
                  :associate_chair,
                  :lab_coordinator
  has_many :committees, dependent: :destroy
  has_many :students, through: :committees
  validates_presence_of :first_name, :last_name, :email
  validates_uniqueness_of :last_name, scope: :first_name
  validates_associated :committees

  def to_param
    "#{id} #{full_name}".parameterize
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  
  def ms_chaired_committees
    students.where('ms_chair = true')
  end
  
  def phd_chaired_committees
    students.where('phd_chair = true')
  end
  
  def chaired?(student)
    students.where('phd_chair = true OR ms_chair = true').include? student
  end
  
  def current_committees
    committees.joins(:student).where("students.status = ?", "Current student")
  end
  
  def past_committees
    committees.joins(:student).where("students.status != ?", "Current student")
  end
  
  def admin?
    department_chair || undergraduate_advisor || graduate_advisor || associate_chair
  end
  
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.order('last_name')

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
    @professor = Professor.find(params[:id])
    @current_committees = @professor.current_committees.order('students.last_name')
    @past_committees = @professor.past_committees.order('students.last_name')
    
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /professors/new
  # GET /professors/new.json
  def new
    @password = (0...8).map{65.+(rand(25)).chr}.join
    @professor = Professor.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /professors/1/edit
  def edit
    @professor = Professor.find(params[:id])
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(params[:professor])

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /professors/1
  # PUT /professors/1.json
  def update
    @professor = Professor.find(params[:id])

    respond_to do |format|
      if @professor == current_professor && params[:password].present?
        if @professor.update_attributes(params[:professor])
          sign_in @professor, bypass: true
          format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        else
          format.html { render action: "edit" }
        end
      else
        if @professor.update_without_password(params[:professor])
          format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        else
          format.html { render action: "edit" }
        end
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor = Professor.find(params[:id])
    @professor.destroy

    respond_to do |format|
      format.html { redirect_to professors_url }
    end
  end
  
  def committees
    @professors = Professor.includes(:students,:committees).order('last_name')
  end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
  
  def job_title(professor)
    if professor.graduate_advisor
      "Graduate Advisor"
    elsif professor.undergraduate_advisor
      "Undergraduate Advisor"
    elsif professor.department_chair
      "Department Chair"
    elsif professor.associate_chair
      "Associate Chair"
    elsif professor.lab_coordinator
      "Lab Coordinator"
    end
  end
  
end

app/views/professors/_committees.slim
table.table.table-striped
  thead
    tr
      th Name
      th E-mail
      th MS/PhD
      th
  tbody
    - committees.each do |committee|
      tr
        td = link_to committee.student.full_name, committee.student
        td = mail_to committee.student.email_1
        td = committee_type(committee)
        td
          - if professor.chaired?(committee.student)
            span.label Chair

app/views/professors/_form.html.slim
= simple_form_for @professor, html: { class: "form-horizontal" } do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :phone
  = f.input :email, label: "E-mail", required: true
  - if current_professor.admin?
    = f.input :department_chair
    = f.input :associate_chair
    = f.input :graduate_advisor
    = f.input :undergraduate_advisor
    = f.input :lab_coordinator
  - if @password.present?
    = hidden_field_tag "professor[password]", @password
    = hidden_field_tag "professor[password_confirmation]", @password
  - elsif @professor == current_professor
    = f.input :password
    span.help-block Leave blank to keep current password
    = f.input :password_confirmation
  .form-actions
    = f.submit "Save", class: "btn btn-primary"
    = link_to "Cancel", :back, class: "btn btn-cancel"

app/views/professors/committees.slim
h1 Current Committees for each Professor
table.table
  thead
  tbody
    - @professors.each do |professor|
      - next if professor.current_committees.empty?
      tr
        td = link_to professor.full_name, professor
        td
          - unless professor.committees.empty?
            table.table.table-bordered
              thead
                tr
                  th Name
                  th MS
                  th PhD
              tbody
                - professor.current_committees.order('students.last_name').each do |committee|
                  - next unless committee.student.current_student?
                  tr
                    td = link_to committee.student.full_name, committee.student
                    td.check == committee.ms_chair ? "Chair" : ok_or_not_ok(committee.ms)
                    td.check == committee.phd_chair ? "Chair" : ok_or_not_ok(committee.phd)

app/views/professors/edit.html.slim
h1 Editing professor
= render 'form'

app/views/professors/index.html.slim
h1 Faculty
form.filterform.form-search.hide-from-pdf action="#"
  = text_field_tag "filterString", nil, class: "input-medium search-query"
  i.icon-remove.clear-search
= link_to 'New Professor', new_professor_path, class: "hide-from-pdf"
table.table.table-striped.list
  thead
    tr
      th Name
      th Email
      th
      th
  tbody
    - @professors.each do |professor|
      tr
        td = link_to professor.full_name, professor, class: "filtered-by target_link"
        td = mail_to professor.email, professor.email, class: "filtered-by"
        td = link_to 'Edit', edit_professor_path(professor)
br

app/views/professors/new.html.slim
h1 New professor
= render 'form'

app/views/professors/show.html.slim
h1 = @professor.full_name
h3 = job_title @professor
p = mail_to @professor.email
p = @professor.phone

h2 Student Committees

.tabbable
  ul.nav.nav-tabs
    li.active
      a href="#1" data-toggle="tab" Current Students
    li
      a href="#2" data-toggle="tab" Past Students
  .tab-content
    .tab-pane.active#1
      = render "committees", {committees: @current_committees, professor: @professor}
    .tab-pane#2
      = render "committees", {committees: @past_committees, professor: @professor}

.form-actions.hide-from-pdf
  = link_to "Back", :back, :class => 'btn'
  = link_to 'Edit ', edit_professor_path(@professor), :class => 'btn'
  = link_to "Delete", professor_path(@professor), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn'