config/routes.rb
GradStudents::Application.routes.draw do
  get "letter/show"

  devise_for :professors
  
  root to: "students#index"
  
  match 'students/incomplete_qualifier' => 'students#incomplete_qualifier'
  match 'students/incomplete_research' => 'students#incomplete_research'
  match 'students/incomplete_citi' => 'students#incomplete_citi'
  match 'students/committees' => 'students#committees'
  match 'students/funding' => 'students#funding'
  match 'professors/committees' => 'professors#committees'
  match 'fundings/edit' => 'fundings#edit', as: :edit_fundings
  match 'fundings/update' => 'fundings#update', as: :update_fundings, via: :put
  resources :professors
  resources :students
  resources :meetings
  resources :letters
  
  

end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    title = content_for?(:title) ? yield(:title) : "GradStudentsDB"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    /! Le styles
    = javascript_include_tag "application"
    css:
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    = stylesheet_link_tag "application", :media => "all"
    / Le fav and touch icons
    / link href="images/favicon.ico" rel="shortcut icon"
    link href="images/apple-touch-icon.png" rel="apple-touch-icon"
    link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"
    link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"


  body
    .navbar.navbar-fixed-top.hide-from-pdf
      .navbar-inner
        .container
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "GradStudentsDB", root_path, class: "brand"
          .container.nav-collapse
            - if professor_signed_in?
              ul.nav
                li= link_to "Students", students_path
                li= link_to "Faculty", professors_path
                li= link_to "Meetings", meetings_path
                li= link_to "Update Funding", edit_fundings_path
                li.dropdown
                  a.dropdown-toggle href="#" data-toggle="dropdown"
                    | Reports
                    b.caret
                  ul.dropdown-menu
                    li.nav-header Students
                    li= link_to "All Committees", students_committees_path
                    li= link_to "Unsatisfied Qualifying Exams", students_incomplete_qualifier_path
                    li= link_to "Unsatisfied Alternate Research", students_incomplete_research_path
                    li= link_to "Incomplete CITI Training", students_incomplete_citi_path
                    li= link_to "View all offer letters (pdf)", letters_path(format: "pdf")
                    li= link_to "Stipend throughout the years", students_funding_path
                    li.divider
                    li.nav-header Professors
                    li= link_to "Current Committees", professors_committees_path
    - if professor_signed_in?
      li.nav-right.hide-from-pdf == "Welcome, #{current_professor.full_name} (#{link_to('logout', destroy_professor_session_path, :method => :delete)} or #{link_to('change password', edit_professor_path(current_professor))})"
    .container
      - if flash[:alert]
        .row
          .span6.offset3
            .alert.alert-error
              a.close data-dismiss="alert" &times;
              = flash[:alert]
      - if flash[:notice]
        .row
          .span6.offset3
            .alert.alert-info
              a.close data-dismiss="alert" &times;
              = flash[:notice]
      .content
        .row
          .span9
            = yield
          .span1 &nbsp;
          .span3
            - if professor_signed_in?
              .well.sidebar-nav.hide-from-pdf    
                ul.unstyled
                  li = link_to "Printer friendly version (pdf)", url_for( format: 'pdf', params: clean_params(params) )
                  = yield(:sidebar)
    
      footer
        p &copy; 2012 Georgia State University Department of Physics and Astronomy
        p.hide-from-pdf = link_to "Fork me on GitHub", "https://github.com/greggroth/grad_students"

app/views/layouts/letter.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    title = content_for?(:title) ? yield(:title) : "GradStudentsDB"
    = csrf_meta_tags
    = stylesheet_link_tag "letters", :media => "all"
    = javascript_include_tag "application"


  body
    .single-page
      .heading
        p#department DEPARTMENT OF PHYSICS AND ASTRONOMY
        ul.heading#contact
          li 29 Peachtree Center Ave
          li Atlanta, GA 30303-3083
          li Phone:   404 / 413-6033
          li FAX:     404 / 413-6025
          li 
          li = @department_chair.full_name
          li = "Phone:   #{heading_format_phone(@department_chair.phone)}"
          li = "E-mail:  #{@department_chair.email}"
      = yield